MVCDemo/MVCDemo.WebClient/Controllers/DemoPersonasController.cs
using MVCDemo.WebClient.BOL;
using MVCDemo.WebClient.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDemo.WebClient.Controllers
{
    public class DemoPersonasController : Controller
    {
        #region GETSViews

        // GET: DemoPersonas
        public ActionResult Index()
        {
            return View();
        }


        #endregion

        #region POSTViews

        #endregion



        #region JSonResults
        public ActionResult GetJsonPersonas()
        {
            try
            {
                PersonasBOL _personasBol = new PersonasBOL();
                List<PersonasDTO> _personas = new List<PersonasDTO>();

                _personas = _personasBol.getAll();

                return Json(_personas, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { IsFail = true, Message = ex.Message });
            }
        }
        #endregion

    }
}

MVCDemo/MVCDemo.WebClient/Views/DemoPersonas/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


<button type="submit" onclick="deleteUsers()" class="bak-button mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" tabindex="0">
    <i class="material-icons">delete</i>
    <span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span>
</button>


<div class="mdl-card mdl-card__base mdl-shadow--2dp" style="width: 100%">
    <div class="mdl-card_header_container">
        <!--heaeder-->
        <h1 class="mdl_card_main_title">
            Demo Personas Con jSON reuslt
        </h1>
    </div>

    <div class="mdl-toolbar">
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">delete</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">add</i>
        </button>
    </div>

    <div class="mdl_card_content2">
        <div id="gridPersonas">

        </div>
    </div>
</div>


<script>
    var urlGetJsonPersonas = '@Url.Action("GetJsonPersonas", "DemoPersonas")';
</script>

<script src="~/scripts/DemoPersonas/index.js"></script>