MVCDemo/MVCDemo.WebClient/Controllers/EstructuraOrganizacional/PersonasController.cs
using MVCDemo.WebClient.Extensions.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AGT.GRC.UI.WebClient.Controllers
{
    public class PersonasController : Controller
    {
        // GET: People
        public ActionResult Index()
        {
            return View();
        }

        #region Po-pup Partial View Get section

        /// <summary>
        /// Getting partial view for creating a user
        /// </summary>
        /// <returns></returns>
        [HttpPost, AjaxOnly]
        public ActionResult GetParcialFormAddUser()
        {
            try
            {
                return PartialView("_PartialFormAddUser");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        /// <summary>
        /// Getting partial view for updating a user
        /// </summary>
        /// <returns></returns>
        [HttpPost, AjaxOnly]
        public ActionResult GetParcialFormUpdateUser()
        {
            try
            {
                return PartialView("_PartialFormUpdateUser");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        /// <summary>
        /// Getting partial view for view user details
        /// </summary>
        /// <returns></returns>
        [HttpPost, AjaxOnly]
        public ActionResult GetPartialDetailUser()
        {
            try
            {
                return PartialView("_PartialGetDetailUser");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        #endregion
    }
}

MVCDemo/MVCDemo.WebClient/Views/Personas/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}


<button type="submit" onclick="show_GetParcialFormAddUser()" class="bak-button mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored" tabindex="0">
    <i class="material-icons">add</i>
    <span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span>
</button>

<div class="mdl-card mdl-card__base mdl-shadow--2dp" style="width: 100%">
    <div class="mdl-card_header_container">
        <!--heaeder-->
        <h1 class="mdl_card_main_title">
            Personas
        </h1>
    </div>

    <div class="mdl-toolbar">
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" disabled>
            <i class="material-icons">save</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">mode_edit</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" disabled>
            <i class="material-icons">delete</i>
        </button>

        <div class="devider"></div>

        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">mode_edit</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" disabled>
            <i class="material-icons">delete</i>
        </button>

        <select class="mdl-textfield__input">
            <option value="value">text</option>
            <option value="value">text</option>
            <option value="value">text</option>
            <option value="value">text</option>
        </select>

        <div class="devider"></div>

        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_align_center</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_align_justify</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_bold</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_size</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_shapes</i>
        </button>

        <div class="devider"></div>

        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">theaters</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">power_settings_new</i>
        </button>
        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">format_shapes</i>
        </button>
    </div>

    <div class="mdl_card_content2">
        <table class="reportntable" id="listaBeneficiarios">
            <thead>
                <tr>
                    <th></th>
                    <th>CODIGO</th>
                    <th>1ER NOMBRE</th>
                    <th>2DO NOMBRE</th>
                    <th>1ER APELLIDO</th>
                    <th>2DO APELLIDO</th>
                    <th>CUENTA DOMINIO</th>
                    <th>DETALLE</th>
                    <th>ELIMINAR</th>
                    <th>ACTUALIZAR</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-label="">
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="check1">
                            <input type="checkbox" id="check1" class="mdl-checkbox__input">
                            <span class="mdl-checkbox__label"></span>
                        </label>
                    </td>
                    <td data-label="Codigo">00000</td>
                    <td data-label="1er Nombre">Nombre</td>
                    <td data-label="2do Nombre">Nombre</td>
                    <td data-label="1er Apelliedo">Apellido</td>
                    <td data-label="2do Apelliedo">Apellido</td>
                    <td data-label="Cuenta Dominio">Dominio/Cuenta</td>

                    <td data-label="Detalle">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" onclick="show_GetPartialDetailUser()">
                            <i class="material-icons">subject</i>
                        </button>
                    </td>
                    <td data-label="Eliminar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" onclick="deleteUser()">
                            <i class="material-icons">delete</i>
                        </button>
                    </td>
                    <td data-label="Modificar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon" onclick="show_GetParcialFormUpdateUser()">
                            <i class="material-icons">mode_edit</i>
                        </button>
                    </td>
                </tr>


                <tr>
                    <td data-label="">
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="check2">
                            <input type="checkbox" id="check2" class="mdl-checkbox__input">
                            <span class="mdl-checkbox__label"></span>
                        </label>
                    </td>
                    <td data-label="Codigo">00000</td>
                    <td data-label="1er Nombre">Nombre</td>
                    <td data-label="2do Nombre">Nombre</td>
                    <td data-label="1er Apelliedo">Apellido</td>
                    <td data-label="2do Apelliedo">Apellido</td>
                    <td data-label="Cuenta Dominio">Dominio/Cuenta</td>

                    <td data-label="Detalle">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">subject</i>
                        </button>
                    </td>
                    <td data-label="Eliminar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">delete</i>
                        </button>
                    </td>
                    <td data-label="Modificar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">mode_edit</i>
                        </button>
                    </td>
                </tr>


                <tr>
                    <td data-label="">
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="check3">
                            <input type="checkbox" id="check3" class="mdl-checkbox__input">
                            <span class="mdl-checkbox__label"></span>
                        </label>
                    </td>
                    <td data-label="Codigo">00000</td>
                    <td data-label="1er Nombre">Nombre</td>
                    <td data-label="2do Nombre">Nombre</td>
                    <td data-label="1er Apelliedo">Apellido</td>
                    <td data-label="2do Apelliedo">Apellido</td>
                    <td data-label="Cuenta Dominio">Dominio/Cuenta</td>

                    <td data-label="Detalle">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">subject</i>
                        </button>
                    </td>
                    <td data-label="Eliminar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">delete</i>
                        </button>
                    </td>
                    <td data-label="Modificar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">mode_edit</i>
                        </button>
                    </td>
                </tr>


                <tr>
                    <td data-label="">
                        <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="check4">
                            <input type="checkbox" id="check4" class="mdl-checkbox__input">
                            <span class="mdl-checkbox__label"></span>
                        </label>
                    </td>
                    <td data-label="Codigo">00000</td>
                    <td data-label="1er Nombre">Nombre</td>
                    <td data-label="2do Nombre">Nombre</td>
                    <td data-label="1er Apelliedo">Apellido</td>
                    <td data-label="2do Apelliedo">Apellido</td>
                    <td data-label="Cuenta Dominio">Dominio/Cuenta</td>

                    <td data-label="Detalle">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">subject</i>
                        </button>
                    </td>
                    <td data-label="Eliminar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">delete</i>
                        </button>
                    </td>
                    <td data-label="Modificar">
                        <button class="item-delete mdl-button mdl-js-button mdl-button--icon">
                            <i class="material-icons">mode_edit</i>
                        </button>
                    </td>
                </tr>

            </tbody>
        </table>

    </div>

</div>

<script>
    //Usuario
    var urlGetParcialFormAddUser = '@Url.Action("GetParcialFormAddUser", "Personas")';
    var urlGetParcialFormUpdateUser = '@Url.Action("GetParcialFormUpdateUser", "Personas")';
    var urlGetPartialDetailUser = '@Url.Action("GetPartialDetailUser", "Personas")';
</script>
<script src="~/scripts/EstructuraOrganizacional/Personas/Index.js"></script>



MVCDemo/MVCDemo.WebClient/Views/Personas/_PartialFormAddUser.cshtml
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_codigo" />
    <label class="mdl-textfield__label" for="_codigo">Codigo</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_first_name" />
    <label class="mdl-textfield__label" for="_first_name">Primer Nombre</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_second_name" />
    <label class="mdl-textfield__label" for="_second_name">Segundo Nombre</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_first_last_name" />
    <label class="mdl-textfield__label" for="_first_last_name">Primer Apellido</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_second_last_name" />
    <label class="mdl-textfield__label" for="_second_last_name">Segundo Apellido</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_cuenta_dominio" />
    <label class="mdl-textfield__label" for="_cuenta_dominio">Cuenta de Dominio</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_mail" />
    <label class="mdl-textfield__label" for="_mail">Correo electronico</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_user_account" />
    <label class="mdl-textfield__label" for="_user_account">Cuenta de Usuario</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_password" />
    <label class="mdl-textfield__label" for="_passwpord">Contrase&ntilde;a</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_confirm_passwprd" />
    <label class="mdl-textfield__label" for="_confirm_passwprd">Confirmar Contrase&ntilde;a</label>
</div>


    <label class="float-label">Estado</label>
    <select class="mdl-textfield__input" required id="_status">
        <option value="" selected="selected" disabled>--Seleccione--</option>
        <option value="Act ">Activo</option>
        <option value="Ina">Inactivo</option>
    </select>


<p class="subtitle-section">Unidad organizacional inicial</p>


    <label class="float-label">Unidad organizacional inicial</label>
    <select class="mdl-textfield__input" required id="_unidad_rganizacional">
        <option value="" selected="selected" disabled>--Seleccione--</option>
        <option value="item_1">item 1</option>
        <option value="item_2">item 2</option>
    </select>


<p>NOTA: (Luego podra asignarlo a otras unidades desde la administracion de unidades iniciales)</p>


<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_start_date" />
    <label class="mdl-textfield__label" for="_start_date">Fecha Inicial</label>
</div>
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_end_date" />
    <label class="mdl-textfield__label" for="_end_date">Fecha Final</label>
</div>

<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="_jefe">
    <input type="checkbox" id="_jefe" class="mdl-checkbox__input" checked>
    <span class="mdl-checkbox__label">¿Jefe o persona a cargo de la unidad organizacional?</span>
</label>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_roles_inciales" />
    <label class="mdl-textfield__label" for="_roles_inciales">Roles iniciales</label>
</div>

MVCDemo/MVCDemo.WebClient/Views/Personas/_PartialFormUpdateUser.cshtml

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_codigo" />
    <label class="mdl-textfield__label" for="_codigo">Codigo</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_first_name" />
    <label class="mdl-textfield__label" for="_first_name">Primer Nombre</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_second_name" />
    <label class="mdl-textfield__label" for="_second_name">Segundo Nombre</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_first_last_name" />
    <label class="mdl-textfield__label" for="_first_last_name">Primer Apellido</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width">
    <input type="text" class="mdl-textfield__input" id="_second_last_name" />
    <label class="mdl-textfield__label" for="_second_last_name">Segundo Apellido</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_cuenta_dominio" />
    <label class="mdl-textfield__label" for="_cuenta_dominio">Cuenta de Dominio</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_mail" />
    <label class="mdl-textfield__label" for="_mail">Correo electronico</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_user_account" />
    <label class="mdl-textfield__label" for="_user_account">Cuenta de Usuario</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_password" />
    <label class="mdl-textfield__label" for="_passwpord">Contrase&ntilde;a</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_confirm_passwprd" />
    <label class="mdl-textfield__label" for="_confirm_passwprd">Confirmar Contrase&ntilde;a</label>
</div>


<label class="float-label">Estado</label>
<select class="mdl-textfield__input" required id="_status">
    <option value="" selected="selected" disabled>--Seleccione--</option>
    <option value="Act ">Activo</option>
    <option value="Ina">Inactivo</option>
</select>


<p class="subtitle-section">Unidad organizacional inicial</p>


<label class="float-label">Unidad organizacional inicial</label>
<select class="mdl-textfield__input" required id="_unidad_rganizacional">
    <option value="" selected="selected" disabled>--Seleccione--</option>
    <option value="item_1">item 1</option>
    <option value="item_2">item 2</option>
</select>

<p>NOTA: (Luego podra asignarlo a otras unidades desde la administracion de unidades iniciales)</p>


<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_start_date" />
    <label class="mdl-textfield__label" for="_start_date">Fecha Inicial</label>
</div>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="password" class="mdl-textfield__input" id="_end_date" />
    <label class="mdl-textfield__label" for="_end_date">Fecha Final</label>
</div>

<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="_jefe">
    <input type="checkbox" id="_jefe" class="mdl-checkbox__input" checked>
    <span class="mdl-checkbox__label">¿Jefe o persona a cargo de la unidad organizacional?</span>
</label>

<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label fixed-width" style="margin-top: 5px">
    <input type="text" class="mdl-textfield__input" id="_roles_inciales" />
    <label class="mdl-textfield__label" for="_roles_inciales">Roles iniciales</label>
</div>

MVCDemo/MVCDemo.WebClient/Views/Personas/_PartialGetDetailUser.cshtml
<link href="~/Libs/MDL/css/GridLayout.css" rel="stylesheet" />
<p class="popup-detail-description">
    <strong>CODIGO</strong>
</p>
<p class="popup-detail-leyend">
    Codigo
</p>

<p class="popup-detail-description">
    <strong>NOMBE COMPLETO</strong>
</p>
<p class="popup-detail-leyend">
    Nombre
</p>

<p class="popup-detail-description">
    <strong>CUENTA DE DOMINIO</strong>
</p>
<p class="popup-detail-leyend">
    Cuenta de dominio
</p>

<p class="popup-detail-description">
    <strong>CORREO ELECTRONICO</strong>
</p>
<p class="popup-detail-leyend">
    Correo electronico
</p>

<p class="popup-detail-description">
    <strong>CUENTA USUARIO</strong>
</p>
<p class="popup-detail-leyend">
    Cuenta de usuario
</p>

<p class="popup-detail-description">
    <strong>ESTADO</strong>
</p>
<p class="popup-detail-leyend">
    Estado
</p>

<p class="subtitle-section">Unidad organizacional inicial</p>

<p class="popup-detail-description">
    <strong>UNIDAD ORGANIZACIONAL INICIAL</strong>
</p>
<p class="popup-detail-leyend">
    Unidad organizacional inicial
</p>

<p>NOTA: (Luego podra asignarlo a otras unidades desde la administracion de unidades iniciales)</p>


<p class="popup-detail-description">
    <strong>00/00/0000</strong>
</p>
<p class="popup-detail-leyend">
    Fecha inicial
</p>

<p class="popup-detail-description">
    <strong>00/00/0000</strong>
</p>
<p class="popup-detail-leyend">
    Fecha final
</p>

<p class="popup-detail-description">
    <strong>SI</strong>
</p>
<p class="popup-detail-leyend">
    ¿Jefe o persona a cargo de la unidad organizacional?
</p>

<p class="popup-detail-description">
    <strong>ROLES</strong>
</p>
<p class="popup-detail-leyend">
    Roles iniciales
</p>